[project]
name = "backend"
requires-python = ">=3.11"
version = "1.0.1"
dependencies = [
    "requests>=2.32.3",
    "starlette>=0.46.0",
    "uvicorn>=0.34.0",
]

[dependency-groups]
dev = [
    "mypy>=1.15.0",
    "pytest>=8.3.5",
    "ruff>=0.9.10",
]

[tool.ruff]
line-length = 120
